on:
  schedule:
    # At 00:00 on Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - uses: actions/checkout@master
      - run: ./build.sh

